from .hierarchical_detection import HierarchicalDetectionTrainer
from .yolo_utils import get_yolo_class_names
import yaml
from importlib import resources
from hierarchical_loss.hierarchy import Hierarchy

COCO_HIERARCHY = {
    'living_thing': 'object',
    'person': 'living_thing',
    'animal': 'living_thing',
    'domestic_animal': 'animal',
    'cat': 'domestic_animal',
    'dog': 'domestic_animal',
    'bird': 'domestic_animal',
    'livestock_animal': 'animal',
    'horse': 'livestock_animal',
    'sheep': 'livestock_animal',
    'cow': 'livestock_animal',
    'wild_animal': 'animal',
    'elephant': 'wild_animal',
    'bear': 'wild_animal',
    'zebra': 'wild_animal',
    'giraffe': 'wild_animal',
    'vehicle': 'object',
    'land_vehicle': 'vehicle',
    'bicycle': 'land_vehicle',
    'car': 'land_vehicle',
    'motorcycle': 'land_vehicle',
    'bus': 'land_vehicle',
    'train': 'land_vehicle',
    'truck': 'land_vehicle',
    'airplane': 'vehicle',
    'boat': 'vehicle',
    'outdoor_and_sports_object': 'object',
    'street_fixture': 'outdoor_and_sports_object',
    'traffic light': 'street_fixture',
    'fire hydrant': 'street_fixture',
    'stop sign': 'street_fixture',
    'parking meter': 'street_fixture',
    'bench': 'street_fixture',
    'sports_equipment': 'outdoor_and_sports_object',
    'ball_sport_equipment': 'sports_equipment',
    'sports ball': 'ball_sport_equipment',
    'baseball bat': 'ball_sport_equipment',
    'baseball glove': 'ball_sport_equipment',
    'tennis racket': 'ball_sport_equipment',
    'board_sport_equipment': 'sports_equipment',
    'skateboard': 'board_sport_equipment',
    'surfboard': 'board_sport_equipment',
    'snowboard': 'board_sport_equipment',
    'other_sports_equipment': 'sports_equipment',
    'frisbee': 'other_sports_equipment',
    'skis': 'other_sports_equipment',
    'kite': 'other_sports_equipment',
    'indoor_object': 'object',
    'furniture': 'indoor_object',
    'chair': 'furniture',
    'couch': 'furniture',
    'potted plant': 'furniture',
    'bed': 'furniture',
    'dining table': 'furniture',
    'appliance_and_electronics': 'indoor_object',
    'appliance': 'appliance_and_electronics',
    'microwave': 'appliance',
    'oven': 'appliance',
    'toaster': 'appliance',
    'sink': 'appliance',
    'refrigerator': 'appliance',
    'toilet': 'appliance',
    'electronics': 'appliance_and_electronics',
    'tv': 'electronics',
    'laptop': 'electronics',
    'mouse': 'electronics',
    'remote': 'electronics',
    'keyboard': 'electronics',
    'cell phone': 'electronics',
    'kitchenware': 'indoor_object',
    'bottle': 'kitchenware',
    'wine glass': 'kitchenware',
    'cup': 'kitchenware',
    'fork': 'kitchenware',
    'knife': 'kitchenware',
    'spoon': 'kitchenware',
    'bowl': 'kitchenware',
    'personal_care_item': 'indoor_object',
    'hair dryer': 'personal_care_item',
    'toothbrush': 'personal_care_item',
    'accessory_and_item': 'object',
    'personal_accessory': 'accessory_and_item',
    'backpack': 'personal_accessory',
    'umbrella': 'personal_accessory',
    'handbag': 'personal_accessory',
    'tie': 'personal_accessory',
    'suitcase': 'personal_accessory',
    'home_and_office_item': 'accessory_and_item',
    'book': 'home_and_office_item',
    'clock': 'home_and_office_item',
    'vase': 'home_and_office_item',
    'scissors': 'home_and_office_item',
    'teddy bear': 'home_and_office_item',
    'food': 'object',
    'fruit': 'food',
    'banana': 'fruit',
    'apple': 'fruit',
    'orange': 'fruit',
    'vegetable': 'food',
    'broccoli': 'vegetable',
    'carrot': 'vegetable',
    'prepared_meal': 'food',
    'sandwich': 'prepared_meal',
    'hot dog': 'prepared_meal',
    'pizza': 'prepared_meal',
    'dessert': 'food',
    'donut': 'dessert',
    'cake': 'dessert'
}

YOLO_DATASET_YAML = resources.files('hierarchical_yolo.models.coco128').joinpath('hierarchicalcoco128.yaml')
with open(YOLO_DATASET_YAML, 'r') as f:
    COCO_YOLO_ID_MAP = get_yolo_class_names(YOLO_DATASET_YAML)

class MSCOCOHierarchicalDetectionTrainer(HierarchicalDetectionTrainer):
    # Hierarchy requires the index -> name map in the other direction
    _hierarchy = Hierarchy(COCO_HIERARCHY, {v: k for k,v in COCO_YOLO_ID_MAP.items()})
